// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeEc7dq5FqpkIQb6Tv3C3XUpMlRNpoga8',
    appId: '1:132597466074:web:82c20534311d18ab3736e3',
    messagingSenderId: '132597466074',
    projectId: 'flutterchatapp-d8b79',
    authDomain: 'flutterchatapp-d8b79.firebaseapp.com',
    storageBucket: 'flutterchatapp-d8b79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6y7FYO_G3urKQcFy_aa6HX4NaplUGUg',
    appId: '1:132597466074:android:d9fc55cf9fc61c4b3736e3',
    messagingSenderId: '132597466074',
    projectId: 'flutterchatapp-d8b79',
    storageBucket: 'flutterchatapp-d8b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMI79oFnlonuZojitdS_xyw7KjPjYL4rY',
    appId: '1:132597466074:ios:290829f19ecfb5d03736e3',
    messagingSenderId: '132597466074',
    projectId: 'flutterchatapp-d8b79',
    storageBucket: 'flutterchatapp-d8b79.appspot.com',
    iosClientId: '132597466074-u23ojanhb4gnrgfj6mfpl0quk4oo6u22.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMI79oFnlonuZojitdS_xyw7KjPjYL4rY',
    appId: '1:132597466074:ios:290829f19ecfb5d03736e3',
    messagingSenderId: '132597466074',
    projectId: 'flutterchatapp-d8b79',
    storageBucket: 'flutterchatapp-d8b79.appspot.com',
    iosClientId: '132597466074-u23ojanhb4gnrgfj6mfpl0quk4oo6u22.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
